### ISSUE TITLE
1.9-0.1 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [FlowstoneTeam/OilCraft#19]
Issue: oil-craft-1.9-0.1 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/16d5daba3d8518f5242c082914e8b7dd

fml server latest:
https://gist.github.com/60c741576b09f28f45c8949b424e2c4b

**Comment by imdutch21** [comment]
it seems like they changed something in the new forge update, if you want to use the mod you'll probably need to use a version below 1820. I will fix this ASAP

**Comment by kreezxil** [comment]
This error is back with Forge build 1863


Issue: oil-craft-1.9-0.1 crashes dedicated forge server 1.9 build 1863 on startup

crash report:
https://gist.github.com/e793ac10c031dfcd7cfb957b28f005a6

fml server latest:
https://gist.github.com/21a31d79a729bdfbaca56275ea0e30b0
